store {
  url = "http://[::1]:5500/"
}
browser {
  browserInTest = "chromium"
  isHeadless = false
  traceEnabled = true
  elementTimeoutMs = 5000
},
users {
  "testUser" = {
    email = "TBC@TBC.com"
    password = "TBC"
  }
}